CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'sjin'@'%' IDENTIFIED BY '4242';
GRANT ALL PRIVILEGES ON wordpress.* TO 'sjin'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '4242';