CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'sjin'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON wordpress.* TO 'sjin'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root12345';